### ISSUE TITLE
[1.2.0] Bindings are not saved after shutdown on macOS

### ISSUE THREAD

**Issue by Nyarumi** [nhielost/obs-midi-mg#1]
Bindings don't save when shutting down and restarting OBS, resulting in having to recreate the bindings every use.
This is on macOS Monterey 12.5.1 with OBS 28.0 RC1 using the universal version of the plugin, on a Macbook Pro 14" with an M1 Max.

**Comment by nhielost** [comment]
Can you locate the `obs-midi-mg-config.json` file located in the `plugin_config` folder? If so, does the file contain the bindings after you shut down OBS but before you restart it? Or is it an empty file?

**Comment by Nyarumi** [comment]
It doesn't exist. According to the logs, it can't seem to write the file:
`22:46:28.673: Failed to load 'en-US' text for module: 'obs-midi-mg'
22:46:28.673: [obs-midi-mg] Loading...
22:46:28.673: os_quick_write_utf8_file_safe: failed to write to /Users/username/Library/Application Support/obs-studio/plugin_config/obs-midi-mg/obs-midi-mg-config.json.tmp
22:46:29.581: [obs-midi-mg] Loading Successful`

**Comment by Estyms** [comment]
Same problem on windows.
It seems like the plugin doesn't create the config folder when it doesn't exists.
If I create it manually it then loads and saves the config fine.

**Comment by nhielost** [comment]
The new release (v1.2.1) should fix this issue. If this continues, please file a new issue for the new update.

Thanks for your feedback! It is much appreciated.
