### ISSUE TITLE
Not seeing the plugin in tools 3.0.0 Beta

### ISSUE THREAD

**Issue by HumanalizerVisualien** [nhielost/obs-midi-mg#102]
Not seeing the plugin in tools 3.0.0 Beta, i try with OBS 30.0.2 and 29.0.2 and Last Ventura/ Sonoma 14.2.1....

Apple MacBook Air 2020 M1, OBS 29.0.2 arm64, obs-midi-mg 2.3.0 arm64, Akai Profesional MIDIMIX

**Comment by nhielost** [comment]
Hello!

For macOS users, the v3.0.0 betas had a bug within the MIDI library that would cause issues with the plugin either crashing or not appearing at all. With the v3.0.0 release, this bug should have been fixed, so please try it out.

If it's still not appearing, please let me know.

**Comment by HumanalizerVisualien** [comment]
Hello dear friend, i just try version 3.0.0 and the plugin shows….but where is the greatest thing? „Custom Filter Settings“ don't show any option to set up, so for me the plugin become complete unusual…whats the problem?  

best regards
raphael
