### ISSUE TITLE
Misses some note ons/offs

### ISSUE THREAD

**Issue by xaionaro** [nhielost/obs-midi-mg#104]
Hello.

I've installed the plugin:
```
xaionaro@void:~$ dpkg -l | grep obs-
ii  obs-midi-mg                                                 2.3.0                                      amd64        obs-midi-mg built using CMake
ii  obs-studio                                                  30.0.1-0obsproject1~lunar                  amd64        OBS Studio for Ubuntu
```

It kinda works, but with one problem. It not always see me pressing a key on the MIDI keyboard. Sometimes it takes about 5 times of pressing the key for the plugin to see that. Here is an example of me trying to switch the scene (you may see I have to press the same key multiple times): https://www.youtube.com/watch?v=APeFKIKW9tA

Here is the configuration of the binding:
![Screenshot from 2024-01-29 04-10-47](https://github.com/nhielost/obs-midi-mg/assets/2349376/8ebb0d87-41be-4a9a-b8cb-3b92f02aa4c4)

The same keyboard works fine with zynaddsubfx, so the problem is not in the keyboard, kernel, alsa or pipewire. Hoping that may be it is possible to make the plugin work so that it switches the scene from the first key press :)

Here is a fragment from OBS logs: https://gist.github.com/xaionaro/88246b016ccecea584f4b77611d02a5b (maybe these "Message received is not acceptable." give any hint :) )

**Comment by nhielost** [comment]
Hello!

Please try the newest version (v3.0.0) and see if you are still having this issue. If I recall, there was an issue that would cause some misfires within the v2.3.0 version. If this is still happening in the new version, please let me know.

**Comment by xaionaro** [comment]
It does work well on v3.0.0. Thanks!
