### ISSUE TITLE
[bug report][3.0beta] message description is lost, when choosing action Category

### ISSUE THREAD

**Issue by lmerkens** [nhielost/obs-midi-mg#106]
(version 3.0.0 beta) In the multi Action Editor a newly added Action looses its description when you choose the action category.
To trigger this strange behavior you hit "+" to create a new Action, fill out the message description and go to the Action Editor and choose a category. -> The message description/title changes to "Untitled Action".
This problem is repeatable as long as you don't select anything else than the Category.
If you change the order and give the title last - it seems to work.
if you duplicate an action an change the title of the duplicate - it works fine also

**Comment by nhielost** [comment]
Hello!

I can reproduce this behavior, and a fix will be available soon.

Thanks for the feedback!

**Comment by lmerkens** [comment]
fixed in 3.0 beta 3
