### ISSUE TITLE
Sliders not work

### ISSUE THREAD

**Issue by xDreams0** [nhielost/obs-midi-mg#12]
Hello,

Already thank you for the correction on several Midi devices in the system.

Now I encounter another problem, but I don't know if it's me or if it's not implemented in the plugin.

I use a Korg NanoKontrol 2, and I have dc sliders that allow me to adjust the volume just by moving the knob up or down on the table.

When I wanted to fill it in the plugin settings, I couldn't get it to work, because it sends several messages on the same section.

I tried to do it in multiple, by entering 1 and 127, in vain, it does not want to work.
The other functions they work, except Slider and Fader

Thanks again for this plugin, it will allow many to finally make OBS work as it should with the right hardware!

**Comment by nhielost** [comment]
Thanks for your persistence in reporting these kinds of things!

To use a slider or a fader:
- Make sure to use the Listen to Message feature to get the correct values
- Click the value/velocity number. This will switch the number to OFF, meaning that any value can be used in place of that number (0-127).
- Once the value is set to OFF, go to the appropriate action and set the action value you want the MIDI value to be used in place of to OFF (or, if it is a word field, set it to Use Message Value).

Hope this helps!

**Comment by xDreams0** [comment]
Thank you very much for your feedback, I managed to make the slider work.

But I now encounter a problem which is very recurrent on all the Midi plugins except that of @cpyarger which makes a soft management of the levels.

I am attaching a video explaining what is happening.

https://user-images.githubusercontent.com/37273978/188873127-34a0ff6d-3816-4c44-8bcb-711e6480a7e7.mp4

When I turn the slider all the way up, the level does indeed reach 0.0 dB, but when I start to go down, the physical slider comes down displaying -34 dB, and when I get to the stop, it goes directly to -inf dB.
When I used the @cpyarger plugin, I did not encounter this problem, the field of operation was wide and I could reach up to -100 dB, just with the physical slider. It wasn't blocking and going straight to -inf dB

**Comment by nhielost** [comment]
Thanks for the reply.

I will take that into consideration. I never realized that the values jumped like that!

**Comment by xDreams0** [comment]
Carefree.

I encountered this problem on MidiControl as well as the other plugins. (except the one in alpha, mentioned above)

So I think you have to be careful, it's in my opinion, a negative point for the sliders, especially quad we want them to be flexible.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest release (v1.4.0). If the issue persists, please create another issue.

Again, thanks for the feedback!
