### ISSUE TITLE
[bug][3.0.0release]OBS crashes when moving a freshly created duplicate of a Binding to another Binding Collection

### ISSUE THREAD

**Issue by lmerkens** [nhielost/obs-midi-mg#121]
Situation is as follows:
I got a Binding Collection "scene switcher" wich contains a total of 28 bindings some in "input mode", some in "output mode" to give visual feedback to my APCmini mkII. 
I now added a KORG nanoPAD2 to my setup (for its smaller size, but mostly for its x/y touch panel). This new Korg Device shows up before the APC mini in the MIDI Devices section of the obs-midi-mg Setup Menu.
APC mini mk2 had Input and Output Status connected
nanoPAD2 PAD has Input Status connected Output Status Unavailable 

To duplicate some of the scene switching bindings to the korg 
* I opened the old "scene switcher" Binding Collection, 
* I duplicated one of the (up to this point working) "input mode" bindings (basically a switch the scene and light some LEDs - Binding)
* and moved it to a new (but already existing) Binding Collection "korgtests", with 3 working bindings assigned with the nanoPAD2. 
* OBS repeatably crashes during the move

After shutting down and restarting OBS all Bindings of the old "scene switcher" Bindings Collection are now bound to the nanoPAD2 (and no longer to the APC Mini) and are of course non functional, since the midi messages have different values.
The Duplicate I tried to move has vanished from the source Binding Collection.
The Duplicate I tried to move has not appeared in the target Binding Collection. 
The Bindings in other Binding Collections are still functional (working with the APC mini and still bound to it)

[obs-crash.txt](https://github.com/nhielost/obs-midi-mg/files/14795744/obs-crash.txt)

sorry I don't know if this bug was newly introduced in the latest release, or if this is a side effect of the newly added midi device with a lower position in the MIDI Devices section. Up to this point I could create Binding Duplicates and move them into other Binding Collections fine.

sorry for the bad news

**Comment by nhielost** [comment]
Hello!

I have found the issue, and a fix is under way.

**Comment by nhielost** [comment]
This has been fixed in version 3.0.1.

Thanks for the feedback!
