### ISSUE TITLE
Custom hotkeys don't appear

### ISSUE THREAD

**Issue by blaplace** [nhielost/obs-midi-mg#13]
Hi,
Third-party plugin hotkeys no longer appear in actions (2). Like the one for source movement by advance scene switcher (1).

*This worked in pre-28.0 version of OBS. Sorry for language. Google translated.

![Capture d’écran 2022-09-07 181741](https://user-images.githubusercontent.com/1904258/188929696-9a3232ca-e4eb-4c6e-94bd-02f364080f03.png)
![Capture d’écran 2022-09-07 181926](https://user-images.githubusercontent.com/1904258/188929723-0d320f04-268e-4416-9fd7-041a92c76f4c.png)

**Comment by nhielost** [comment]
Thanks for the feedback.

Unfortunately, I am not seeing those hotkeys coming from Advanced Scene Switcher. However, I am not used to the newest version of it yet, so maybe I am missing something.

Also, I am aware that a lot of hotkeys are missing, and you have now put it into the forefront of issues - this should be an easy fix.

**Comment by blaplace** [comment]
Glad to help however I can.

These hotkeys actually appear once a filter has been created on a scene for advance scene switcher. Before 28.0 you could bind any hotkeys created dynamically by other plugins.

It's little things I think if only I knew how to code in c I would be happy to help.

Else it would be nice to be able to show/hide a scene filter as we can currently do on a source filter. For example in advance scene switcher you can trigger a movement in a scene just by displaying the filter concerned which is hidden by default.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest release (v1.4.0). If the issue persists, please create another issue.

Again, thanks for the feedback!
