### ISSUE TITLE
Suggestion: multiple actions mapped to value of single message (mute/unmute)

### ISSUE THREAD

**Issue by mishakim** [nhielost/obs-midi-mg#14]
As far as I can tell, to set up a toggle control where the controller remembers its state, you have to create two separate bindings, one for the "on" value and one for the "off" value, and assign them to opposite actions (e.g., mute and unmute). It would be helpful to combine those into a single binding, either by allowing different actions to match different control values, or by assuming (or setting) that 0=off and 127=on and applying that logic to binary actions like un/mute, play/pause, etc.

**Comment by nhielost** [comment]
Thanks for the suggestion! I don't know why I didn't implement this from the beginning.

**Comment by nhielost** [comment]
This suggestion was added in the latest release (v1.4.0).
