### ISSUE TITLE
Source scale doesn't scale with CC Values

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#15]
I have a number of Color Sources. Each colored rectangle is programmed via midi cc to represent one of various midi expression/sustain/sostenuto/una corda pedals. All of these pedals are variable resistor and send CC's values from 0-127 on their programmed channels.
With the cpyarger midi plugin under OBS v27 I could depress the pedals and as I would go from 0 to 127 the scale of the Color Source would increase from nothing (not visible) to a rectangle of a size specified on the obs-midi dialogue, Max width and Max height. So cpyarger would use the 0-127 input values to represent 0-100% of the Max sizes specified on the dialogue.

When I use your plugin, I can get sources to rotate smoothly from 0-360 degrees and control where it stops based on the position of my slider when I set the Value set to OFF on the binding message and binding action. But with Rotate Source, with value set to OFF in both message and action, when I press the pedal to full (should transmit 127) the Color Source sizes to about an inch in height and 1/4 inch in width (I'm not sure where it is getting those values...) BUT, when I move my Expression pedal to 0, the Color Source remains unchanged and won't budge any more, unless I edit the action Rotate X and Y to be 0.2 (it doesn't seem to allow 0) and then the Color Source will scale down to 0 upon pressing the pedal (no matter which way I press the pedal). It seems to behave like an on/off switch. Please note: I am never able to size the Color Source to ANYTHING but Maximum or Nothing no matter how gently I move the expression pedal.

I've recorded a video of Obs 27 using the cpyarger plugin to show how responsively and smoothly this works when converting the input to a percentage and allowing the user to specify max and minimum scale values. Hope this helps.

I really appreciate your creating this plugin, as the cpyarger obs-midi plugin seems to have stopped development, has had numerous small bugs since the last version (Mar of 2021) and doesn't currently work on OBS 28...
Please let me know if there is anything I can do to help you better this valuable plugin.

https://user-images.githubusercontent.com/50305507/189607397-8ce0d335-ce42-431b-80e2-3777fe73c1f3.mp4

**Comment by nhielost** [comment]
Thanks for the feedback!

This is a very well written and displayed view of an issue that I was actually going to tackle next. The Source Scale action is actually not working correctly with the MIDI values for some reason, and it should be fixed appropriately soon.

**Comment by lcalder** [comment]
Much appreciated!

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v1.4.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
