### ISSUE TITLE
OBS crash immediately upon launch - with obs-midi-mg latest 1.3.0

### ISSUE THREAD

**Issue by LMWCoding** [nhielost/obs-midi-mg#16]
I read there was a crash issue with previous plug in release and should have been fixed in 1.3.,0.  I installed all the latest version 1.3.0  yesterday.  After installation, it actually worked.  I did some configurations and was able the see an MIDI input controlling OBS.  However, after I shutdown PC and launch OBS today, the OBS crashes upon starting.    Now I have uninstalled the obs-midi-mg and OBS starts up normally.

Here are the first few lines of OBS crash log
'''
Unhandled exception: e06d7363
Date/Time: 2022-09-15, 10:01:42
Fault address: 7FFBA6AE4FD9 (c:\windows\system32\kernelbase.dll)
libobs version: 28.0.1 (64-bit)
Windows version: 10.0 build 19042 (release: 2009; revision: 1889; 64-bit)
CPU: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz

Thread 5930: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
00000042C219D6D0 00007FFBA6AE4FD9 000002367E6B0910 0000000000000000 000002367E0928B0 00007FFB55C70D34 kernelbase.dll!0x7ffba6ae4fd9
00000042C219D7B0 00007FFB960C66C0 00007FFB960B5CE0 000002367E0E8FD0 000002367E0E8FD0 000002367E520D10 vcruntime140.dll!0x7ffb960c66c0
00000042C219D810 00007FFB55C73DEA 000002367E7D6EB0 00000042C219DCB9 FFFFFFFFFFFFFFFF 00000000FFFFFFFF obs-midi-mg.dll!0x7ffb55c73dea
00000042C219D9E0 00007FFB55C6D2CC 000002367E520D10 00000042C219DCB9 000002367E4D5490 000002367E4D5B68 obs-midi-mg.dll!0x7ffb55c6d2cc
00000042C219DBF0 00007FFB55C6AAEC 00000000FFFFFFFF 000002367E0929D0 000002367E7D6990 000002367E7D5230 obs-midi-mg.dll!0x7ffb55c6aaec
00000042C219DD20 00007FFB55C75BB8 000002367E4F59A0 000002367E8164F0 000002367E4D4B60 000002367E4F59A0 obs-midi-mg.dll!0x7ffb55c75bb8
00000042C219DE90 00007FFB5A938051 00000042C219DFF0 0000000000000001 00000042C219DF60 00000042C219DFF0 obs.dll!obs_init_module+0x51
00000042C219DEC0 00007FFB5A9375FB 0000023672307D01 0000023672307D01 000002367E4F59A0 000002367E82B300 obs.dll!load_all_callback+0xab
00000042C219DEF0 00007FFB5A937E76 00007FFB5A937550 00000042C219DFF0 000002367E7235C0 0000000000000000 obs.dll!obs_find_modules2+0x336
00000042C219DFD0 00007FFB5A938119 0000023672302740 00007FF7DA818258 000002366E261A40 0000000000000001 obs.dll!obs_load_all_modules2+0x39
00000042C219E020 00007FF7DA652855 000002366E363390 000002366E363390 FFFFFFFFFFFFFFFF 00000042C219F600 obs64.exe!OBSBasic::OBSInit+0x4b5
00000042C219F060 00007FF7DA5BE0D4 000002366E2FC7B9 FFFFFFFFFFFFFFFF 00007FF7DA804748 000002366E2B2BE0 obs64.exe!OBSApp::OBSInit+0x384
00000042C219F3C0 00007FF7DA5C60F7 0000000000000000 000002366E2D8250 0000023600000000 0000000000000001 obs64.exe!run_program+0xa67
00000042C219F720 00007FF7DA5C89A0 0000000000000000 0000000000000000 0000000000000000 FFFFFFFFFFFFFFFF obs64.exe!main+0x6d0
00000042C219F8F0 00007FF7DA7D4B27 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!WinMain+0x157
00000042C219F980 00007FF7DA7D42B2 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!__scrt_common_main_seh+0x106
00000042C219F9C0 00007FFBA8EB7034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffba8eb7034
00000042C219F9F0 00007FFBA9062651 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffba9062651

'''

**Comment by nhielost** [comment]
Thanks for the feedback!

Could you also post the log file associated with the crash? This will help in identifying the issue.

**Comment by nhielost** [comment]
Also, does it work on the newest release (v1.4.0)?

**Comment by LMWCoding** [comment]
[Crash 2022-09-16 12-46-06.txt](https://github.com/nhielost/obs-midi-mg/files/9580782/Crash.2022-09-16.12-46-06.txt)

I have installed v.1.4.0 and see the same problem.  Attached is the log with the v1.4.0

**Comment by nhielost** [comment]
Sorry if I was unclear, but I meant the actual log file, not the crash log file.

**Comment by LMWCoding** [comment]
I think I found more information to what is causing the problem, it is failure to open midi input port, when the midi device is not plugged in.  Here are my tests
I am using an Android Phone USB connection as a MIDI Controller.  
1) Initially, I have the phone MIDI plugged in ready, then launched OBS, and in obs-midi-mg set the specific MIDI device as ACTIVE.  So it worked that first time.  Then I quit OBS.   After that, I unplugged the MIDI controller (android phone), and launch OBS, that when the crash happened.
2) Now, if I plug in the MIDI controller (android phone), then I launch OBS, it goes in the obs-midi-mg works.
So I think the crash happens obs-midi-mg tries to connect to a disconnected MIDI device.
3) Then I tried to set a virtual port created by loopmidi.  Even if I have not launched loopmidi, meaning the virtual port is actually reported as DISCONNECTED by obs-midi-mg, it does not crash.  So it is not a case that obs-mini-mg will crash with all disconnected midi ports.  It only happened with the default windows midi drivers (from what I know, that's the default drive used by android phone, becuase there is no phone specific midi driver).

This is confirmed by the log (sorry I posted the wrong log earlier).  For the case of crashed, there are the last few lines
20:38:40.341: [obs-midi-mg] Main -> Loading plugin...
20:38:40.341: [obs-midi-mg] Config -> Loading configuration...
20:38:40.342: [obs-midi-mg] Config -> Loading configuration file data from C:/Users/man_wei_lee/AppData/Roaming/obs-studio/plugin_config/obs-midi-mg/obs-midi-mg-config.json...
20:38:40.342: [obs-midi-mg] Config -> Configuration file data loaded. Extracting...
20:38:40.342: [obs-midi-mg] Config -> Configuration file data extraction complete.
20:38:40.342: [obs-midi-mg] Config -> Configuration loading complete.
20:38:40.486: [obs-midi-mg] Device {MIDI function 1} -> Opening input port...

**Comment by LMWCoding** [comment]
sorry, made  a slight mistake above testing.  Point 3.  When I use virtual midi port created by loopmidi, I get same problem of crash.  When a launch loopmidi, hence port is now active, then I launch OBS, OBS would not crash.
But if I close loopmidi, hence port is now disconnected, then I launch OBS, OBS would crash.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v1.4.1). If this issue persists, please create another issue.

Again, thanks for the feedback!
