### ISSUE TITLE
Rotate Source doesn't accept Magnitude of 1 upon inital setup

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#17]
Rotate Source keeps setting the Magnitude to 0 when first setting up a new action.
I set up 5 different midi pedals to each scale a different color source with the value fields set to OFF in the Message and Action bindings.
However, when I initially set up each scale video source action (start x and y both set to "OFF" and Magnitude set to "1") my color source simply wouldn't react at all..
For each pedal I tried fiddling with the x and y settings but still nothing.
I tried checking the color source settings in Ctrl-E transform dialogue, but still nothing.
Then I tried setting the Magnitude to a large value and suddenly my source would scale enormously with my pedal presses!
After that, when I set the Magnitude to "1" (which was my desired objective all along) everything worked.
I tried this on each of the 5 pedals I set up until I found out that the magic trick was to first set the Magnitude to an outrageous value before setting it to "1".

I checked out whether the settings would remain between launches of OBS and all works fine... So, a minor inconvenience in initial setup, but then it works!
Thank you, thank you for bringing this functionality up to OBS v28!!!

PS: I also have a nagging feeling that when initially setting up the "Scale Source" action in the Options dropdown then selecting the scene and source, the dialogue had mysteriously switched to the "Rotate Source" action all by itself. After that I reselected "Scale Source" and reselected my scene and source (unfortunately those seem to get reset every time you change the Options) and got access to the Scale X and Scale Y and Magnitude fields, after which the above problem took place.
It might have been my imagination playing tricks on me... perhaps I had actually accidently selected "Rotate Source" instead of "Scale Source" on the setup of each of the 5 pedals in a row ---, or there just might be another little bug lurking in the action setup UI when selecting "Options"...

**Comment by nhielost** [comment]
Thanks for the feedback!

Sorry about that. I just realized that I forgot to add a default magnitude value for the action. The one shown in the UI doesn't automatically set the one in the configuration file.

**Comment by lcalder** [comment]
Sounds good.
I will now try on MacOS and will watch myself carefully to see if the Rotate Source still occurs or if it is a figment of my imagination and poor clicking skills..

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v1.4.1). If this issue persists, please create another issue.

(If the Rotate Source issue comes up, just file that as a new issue as well.)

Again, thanks for the feedback!
