### ISSUE TITLE
OBS crash on launch if another program is using midi device

### ISSUE THREAD

**Issue by Petter005** [nhielost/obs-midi-mg#18]
I use an electric drumset to control some things inside OBS but to make it work i use my midi drum inside Reaper and output the notes to loopmidi so i can use it in clone hero and obs at the same time but to make it stop crashing I have to "release" the midi device from Reaper, open OBS and then turn my drumkit off and then on and then activate it on Reaper again and everything works fine.

Its not a lot of problems to make it work but if the obs-midi-mg had the option to not use a particular midi device or not use any until you activate it inside obs that would make everything better and prevent any crashes

**Comment by nhielost** [comment]
Thanks for the feedback!

Does the new update (v1.4.1) solve your problem, or is there another underlying issue?

**Comment by Petter005** [comment]
Its working fine now in v1.4.1, i had problems with v1.4.0 when i selected filter as action there was no source list but it seems to be fixed on v1.4.1 too
