### ISSUE TITLE
Source Scale is broken again...

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#19]
-Newly created "Video Source" -> "Source Scale" actions don't allow the Scale X and Scale Y to be '---'.
-Trying to set the numbers using the left and right arrow buttons is a pain and it would be great if one could just type a number instead of a bjillion clicks. 
-Also going below 0 using the arrow buttons can put a strange number like "2 7 eh" or something in the number field. It looks like a memory buffer overrun.

All my colors sources which use Source Scale and which were entered using the previous version still work, and show the '---' for Scale X and Scale Y.
"OFF" no longer shows in this new version in the message nor action dialogues, so it looks like they were changed, but may have introduced a bug...

Thanks for all your hard work on this. This plugin really makes moving to OBS v28 a possibility. If there's anything I can do, don't hesitate to ask.

![image](https://user-images.githubusercontent.com/50305507/191909009-b852ada5-c164-4bc7-9fae-93af2825e7bd.png)

![image](https://user-images.githubusercontent.com/50305507/191909679-c13f6bf9-442c-4d07-8dbd-ba9e64a64fb2.png)

**Comment by nhielost** [comment]
Thanks for the feedback and persistence!

First, to solve the problem. To get the "---" or OFF equivalent, simply click the button to the left of the number that has the label. This has the same behavior as clicking the number (before v1.4.1) and setting it to OFF.

Second, why this is now the case. Clicking the number has posed some difficulties for me, particularly in consistency. It is very out of the way to implement the clicking feature, and it is not an obvious feature as there is no way of showing that the number is clickable. That is why I have moved away from the clickable numbers to the button labels.

Third, the word OFF in the number field doesn't fit in the design in my opinion, so I changed it to a more recognizable format in the three dashed lines. It means exactly the same thing as OFF did.

Fourth, I really like the idea of typing a number in, and I may try to implement that.

Fifth, the Source Scale action overflow error will be solved in the next release as I have confirmed that.

Lastly, you actually just showed me an entirely different issue that I forgot to fix with the button labels, so thanks for that.

I really appreciate the support from you! I'm glad that people like you can help in the development process.

**Comment by HumanalizerVisualien** [comment]
Hello, thx so much to create a new midi-plugin, cuz it looks like the developer from the first one lost him motivation...no wonder, there was over 20'000 downloads but only one donation for 1$ monthly...so please people, help to this developer to keep him motivation with @least a little donation...
I just start to test this one, if "my" two important parameters (Set Source Scale & Rotate Source) work on a fader, i will donate direct 20$...

**Comment by nhielost** [comment]
This issue has been resolved as of the latest release (v1.4.2). If the issue persists (I hope not), please create another issue.

Again, I seriously cannot thank you enough for the support in developing this plugin, especially for the Source Scale action.
