### ISSUE TITLE
[1.2.1] Plugin installs into wrong OBS folder on macOS

### ISSUE THREAD

**Issue by Nyarumi** [nhielost/obs-midi-mg#2]
The plugin should be installed into the user's OBS folder which is found within the local `Library` folder (e.g. `/Users/username/Library/Application Support/obs-studio/plugins`, but is instead installed into the global `Library` folder (e.g. `/Library/Application Support/obs-studio/plugins`), requiring the user to manually move the plugin to the correct folder. After moving, the plugin functions normally.

**Comment by nhielost** [comment]
Can the install location be changed by the installer, or will the installer not give the option to change the install location?

If it doesn't, this issue may take some time as I will have to learn how to interpret the installer file.

**Comment by Nyarumi** [comment]
The default macOS installer doesn't normally have installation options presented by default (at least in my experience on a single user system). There can be options on where to install it to, but only at the system, user, or external disk level. What's strange is that I can get it to install to the correct location, but only if I manually check the installation location options, even though I don't change anything.

Here’s a video on how to get it to install correctly. Since it's in Japanese, here's a little breakdown of what's happening:
First, when I choose to install, it skips over the install location option, which I circle with my mouse in the top left.
Second, I manually go back to the install location options where it shows the three locations options: install to every user, just this user, and install to another disk. Note that I can't actually change this option since the other two are greyed out.
Finally, I just continue the installation like normal and it works. When installing it like normal, you have to authenticate since it's trying to put the file at the system level, but here that doesn't happen since it's installing to my user folder.

I've never seen this happen before honestly. It may not even be your fault, it could just be a weird quirk with the macOS installer. If you can't figure out how to fix it, just writing an explanation on how to install it properly should be fine.

https://user-images.githubusercontent.com/24418563/187096852-e161e143-a14c-41f2-aa8e-051a1cf4c2b6.mov

**Comment by nhielost** [comment]
The newest update (v1.2.2) has addressed this issue. The README now has similar instructions to that of this discussion.

Again, thanks for the feedback!
