### ISSUE TITLE
déconnexion/reconnexion 

### ISSUE THREAD

**Issue by morganplancot** [nhielost/obs-midi-mg#20]
Bonjour,

Possible de mettre la possibilité que le plugin reconnecte correctement le matériel sur OBS sans devoir redémarré OBS

exemple: le plugin fonctionne sur OBS je débranche/rebranche mon launchpad ca ne fonctionne plus

**Comment by nhielost** [comment]
Thanks for the feedback!

I will implement this by the next update.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.0.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
