### ISSUE TITLE
Device not detected

### ISSUE THREAD

**Issue by Mindcontrol-dnb** [nhielost/obs-midi-mg#22]
I've plugged two of my Midi Devices (Akai LPD8 & M-Audio Oxygen 25) into the PC but none of them were detected by the plugin.

Windows Device Manager says that they are connected and detect them with correct name and drivers.

Any solutions on that ? OBS Version is 28.0.3 (64 Bit) on Windows 10 V 21H2

Greets
Sven

**Comment by nhielost** [comment]
Thanks for the feedback!

I am unaware of any issues with connecting devices on Windows at this point, but something may have come up in your case.

Could you provide the log file from OBS to confirm this?
