### ISSUE TITLE
Where´s the midi learn?

### ISSUE THREAD

**Issue by dunholy** [nhielost/obs-midi-mg#24]
I was using the alpha with obs27. Crashed a lot, but I still managed to make it work.
Now using the 1.4.2 version with Obs28.
The interface seems like a huge downgrade, unless I´m missing something. 
Where´s the midi learn guys?

**Comment by dunholy** [comment]
Seems like I found it, but it goes on and off. Doesn´t detect any of my control surfaces, at least not consistently. When I try to close the obsmidi screen it says it can´t because the devices are being "listened". Lol, this is frustrating.

**Comment by dunholy** [comment]
Oh I see obsmidi-mg is not the same as obsmidi. Listen, your interface is obsolete and frankly very mediocre. At the very least you guys should rename the "return" button as "go back". I did found the "midi learn" but couldn´t hook up my midi keyboard, so I went back to OBS27 with obsmidi alpha.

**Comment by nhielost** [comment]
Thanks for the feedback. 

Firstly, what exactly is not working with the listening feature? Are the messages not coming in? Are they wrong? Something else?

Secondly, I have gotten many complaints about the interface, and this is being addressed. A simpler interface is coming soon.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.0.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
