### ISSUE TITLE
Can't change source filter settings with midi

### ISSUE THREAD

**Issue by OneWeb** [nhielost/obs-midi-mg#25]
Hello,

Firstly, love the plugin. Having tried most midi plugins for OBS this one is looking excellent. Well done.

This might be more of a feature request than an issue but I would like to be able to control a source's filter settings with midi. For example, I have a video source with a Luma Key filter applied. Is it possible to configure an action in obs-midi-mg to change this filter's "Luma Max" setting? When creating an action I see I can setup something like:

Category: Filters
Options: Toggle Filter Display
Source: *My video source*
Filter: Luma Key

This is great for toggling the filter on and off but I would love:

Category: Filters
Options: Filter Setting Value
Source: *My video source*
Filter: Luma Key
Setting: *choice of Luma Max, Luma Max Smooth, Luma Min, Luma Min Smooth*

Might this be possible already or could it be added? Looking to control some sweet filter settings via midi control knobs.

Thanks, and great plugin again!

**Comment by nhielost** [comment]
Thanks for the feedback! I appreciate it.

Custom filter settings are unfortunately not implemented currently. However, I have personally thought about this for quite some time. I can't say for sure (there is a hefty update coming), but I'll try to include a feature like this soon.

**Comment by OneWeb** [comment]
Amazing, thanks for the response.

All makes sense. This is a feature I would love and have been using a lot in my streams in the past. Until OBS 28 I was using https://github.com/lebaston100/MIDItoOBS which can do this but is, unfortunately, it's not compatible with the newer versions of OBS.  Thought I'd post in case the source code helps you implement this feature. 😄 

Keep up the good work!

**Comment by HumanalizerVisualien** [comment]
Yea this would make my Setup sooo much more easy, actualy i have to set for exampel 10 luma filters with different values, then to map them all with 10 bindings on one fader...if you can do this, i spend one more time 20$...
question, are you in contact with the creator of obs-midi? thanks him too for the pre-work on this plugin, but i hope he is not rewriting a new version of him obs-midi plugin, that will make no sense, cuz this one is realy top...!

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.2.0).

Again, thanks for the feedback!

**Comment by OneWeb** [comment]
Amazing! I can't wait to try it. Thank you so much 👍
