### ISSUE TITLE
Support for multiple devices simultaniously

### ISSUE THREAD

**Issue by ThrottleLP** [nhielost/obs-midi-mg#26]
I have multiple midi devices that I want to use with OBS (e. g. one controller with faders for audio, another one with many buttons for source toggling,...). Currently only one device can be active. Is it possible to add multi device support in the future?

**Comment by nhielost** [comment]
Thanks for the feedback.

Unfortunately, multi device support has been discontinued due to driver issues. But, you can use another program (like loopmidi) that can assign those devices to a virtual port, and that virtual port can be used in the plugin as a single device.

Hope this helps!

**Comment by nhielost** [comment]
This issue has marked as solved.

Again, thanks for the feedback!
