### ISSUE TITLE
Endless Scrolling...

### ISSUE THREAD

**Issue by HumanalizerVisualien** [nhielost/obs-midi-mg#28]
https://user-images.githubusercontent.com/110275767/197544159-ca9ba32c-0dca-433b-a3e8-4077b497663a.mov

Hi, here a little Issue, i have to scroll down long ways...  

But no problem, it can't affect my happiness about this plug-in..! Thx..

**Comment by nhielost** [comment]
Thanks for the feedback!

I have never seen that before! I'll look into it.

**Comment by nhielost** [comment]
Does this issue continue into the 2.x versions? I know the 1.x versions were a little finnicky as far as dropdowns are concerned.

**Comment by HumanalizerVisualien** [comment]
Yes here the actual issue in 2.1.1...it happen specific in the "Filter"-section-> pulldown-menue -> Source
Like you can see in the screenshots, i have to scroll two full black columns...but hey, no problem, with the new amazing copy/past function i find other ways...1000 thx

<img width="988" alt="Filter1" src="https://user-images.githubusercontent.com/110275767/202853478-36dbc6e3-ebbe-4ef1-9aef-c913545c76d0.png">
<img width="984" alt="Filter2" src="https://user-images.githubusercontent.com/110275767/202853482-8c213901-482b-4b44-8a5e-d73d07967754.png">
<img width="987" alt="Filter3" src="https://user-images.githubusercontent.com/110275767/202853483-db9f3f43-eac8-4a52-8d47-2b5188f3d6f7.png">
<img width="988" alt="Filter4" src="https://user-images.githubusercontent.com/110275767/202853485-7362a51f-e5fe-4e42-ae8a-1ea6b2515572.png">

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.2.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
