### ISSUE TITLE
Fadding music

### ISSUE THREAD

**Issue by carlosrodriguesIT** [nhielost/obs-midi-mg#29]
Hello,

I would like to ask if possible to someone describe the steps that need to performed to control an audio track on OBS with a Rotary potentiometer? 

Isn't clear for me the steps that I need to configure on the plugin to achieve this simple task.

Thanks in advance.

Regards

**Comment by nhielost** [comment]
Thanks for the response!

Unfortunately, I am unaware of how this hardware works. The only thing I can say is to use the *Listen to Message* feature if the device is being recognized by the plugin, then set the action to control the audio as normal.

**Comment by nhielost** [comment]
This issue is being closed due to inactivity.
