### ISSUE TITLE
Plugin crashes OBS v28.0.0-rc2 on windows 11

### ISSUE THREAD

**Issue by Willsie-Digital** [nhielost/obs-midi-mg#3]
Windows Version : 22H2
Build: 22621.575
OBS Version: 28.0.0-rc2

OBS Crashes on launch when plugin is installed

[CrashLog.txt](https://github.com/nhielost/obs-midi-mg/files/9467040/CrashLog.txt)

**Comment by nhielost** [comment]
Could you post the normal log file as well? This will help me further identify the issue.

**Comment by nhielost** [comment]
The newest update (v1.2.2) has addressed this issue. If this issue persists, please create a new issue for that update.

Again, thanks for the feedback!
