### ISSUE TITLE
Active Device always defaults to first in the list

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#31]
I have many midi devices on my system. However, I only use a certain virtual device to communicate with OBS.
Would there be a way to for the plugin to remember the last device used, or perhaps auto select the first device that actually has bindings?

I can't thank you enough for this amazing plugin. It just keeps getting better!

**Comment by nhielost** [comment]
Thanks for the feedback!

Yes, this will be an easy fix.
This plugin would not be the same without your help!

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.1.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
