### ISSUE TITLE
Update 2.1.0 Big Problems

### ISSUE THREAD

**Issue by HumanalizerVisualien** [nhielost/obs-midi-mg#35]
First, thx for your incredible work...version 2.0.0 was great, even if i had to remap my controller with around 400 bindings, cuz of course, i optimize it every new build...

- But now with 2.1.0, all the faders and potis does not work, also the configured send midi to LED's...
- So i reinstall 2.0.0, and ok, first i don't delete the 2.1.0 files, so it shows still the newest update in preferences
- So i reinstall 2.0.0 again, this time i delete the files in my application folder and it shows the right version...but big surprise...
- importing the 2.0.0 bindings-file witch i export BEFORE updating on 2.1.0 fail completely, like a empty file! 
- Check for Updates-Button does not work on 2.1.0

So, i have to restore my system, guess that will fix it...

Apple MacBook Air 2020 M1, Ventura 13.0, OBS 28.1.2 arm64, Akai Profesional MIDIMIX

**Comment by HumanalizerVisualien** [comment]
So here what i find out:

- No visible changes in the bindings-list or even empty list after importing bindings -> just need to close the window

https://user-images.githubusercontent.com/110275767/200673983-c53ff4e9-12a0-402a-9709-25c96138200e.mov

**Comment by nhielost** [comment]
Thanks for the fast feedback!

I am aware of the importing bindings issue and the Check for Updates button issue, but is there something else that I'm not aware of that is wrong? What about 2.1.0 is not working for you?

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.1.1). If this issue persists, please create another issue.

Again, thanks for the feedback!
