### ISSUE TITLE
Release 2.1.0 OBS crash when click "Setup" | MacOS Ventura | Apple M1

### ISSUE THREAD

**Issue by birdbyrd** [nhielost/obs-midi-mg#36]
Hi ! thanks for awesome plugin. Looking forward to play around with it.

I have a problem try to setting up the plugin.

Plug In version 2.1.0
OBS version 2.28.1.1
Mac M1 with Ventura OS

The attach file  is the message from crash report. 
[obs-crash-mac-m1.log](https://github.com/nhielost/obs-midi-mg/files/9971344/obs-crash-mac-m1.log)

Let me know if there is another log that I can retrieve and will be more useful to you.

**Comment by nhielost** [comment]
Thanks for the feedback!

Does this happen every time you open it or is it a one time issue? Also, could you provide the normal log file that OBS produces?

**Comment by birdbyrd** [comment]
it happens every time. Here is the obs log file:

[2022-11-09 20-01-36.txt](https://github.com/nhielost/obs-midi-mg/files/9972872/2022-11-09.20-01-36.txt)

**Comment by nhielost** [comment]
Does the new update (v2.1.1) fix this, or does it continue happening?

**Comment by HumanalizerVisualien** [comment]
Apple MacBook Air 2020 M1, Ventura 13.0, OBS 28.1.2 arm64, obs-midi-mg 2.1.1 arm64, Akai Profesional MIDIMIX

no problems to me, also with previous versions...some times it crash when i create to fast more then one new bindings without setting parameters...

**Comment by birdbyrd** [comment]
@nhielost appreciate you afford ! I can open the set up modal now.
Haven't tried set up any midi trigger yet, will let you know if I found any other issue.

Thank you so much!

**Comment by birdbyrd** [comment]
@nhielost already did some quick test. it's awesome.
Thanks again. You may close the ticket 😀
