### ISSUE TITLE
Magnitude doesn't save between OBS launches

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#37]
Thanks so much for the 2.1.0 update. The plugin is really taking shape!

For Source Scale, the Magnitude fixed setting will always reset to 0 upon launching OBS for all bindings.

Also, I'm wondering whether the Move Source plugin could benefit from a Magnitude setting... Otherwise the range of motion 0-127 maps to is limited by the original source dimensions...??

Thanks again for this wonderful plugin. It now easily exceeds the capabilities and ease-of-use of the original obs-midi plugin.

**Comment by nhielost** [comment]
Thanks for the feedback and praise once again. 

The magnitude error has been corrected. Also, I like the idea of adding magnitude to other actions - I'll look into it.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.1.1). If this issue persists, please create another issue.

Again, thanks for the feedback!
