### ISSUE TITLE
v2.1.0 x64bit crashes on obs launch~

### ISSUE THREAD

**Issue by JoqniX** [nhielost/obs-midi-mg#38]
hewwo~ i tried updating the plugin today~ and it seems to crash on startup for me when launching obs~ 

here are the crash log files~ when this occurred~
dunno what is the cause for the plugin to crash like this? if you do know why do lmk~ 

apparently it is running fine on a fresh obs v28.1.2 ~ but it crashes on main obs ;w; 

[Crash 2022-11-11 06-49-42.txt](https://github.com/nhielost/obs-midi-mg/files/9985689/Crash.2022-11-11.06-49-42.txt)
[Crash 2022-11-11 06-50-36.txt](https://github.com/nhielost/obs-midi-mg/files/9985690/Crash.2022-11-11.06-50-36.txt)
[Crash 2022-11-11 06-51-22.txt](https://github.com/nhielost/obs-midi-mg/files/9985691/Crash.2022-11-11.06-51-22.txt)

**Comment by JoqniX** [comment]
yesh here you go~ 
[2022-11-11 20-35-36.txt](https://github.com/nhielost/obs-midi-mg/files/9991125/2022-11-11.20-35-36.txt)

**Comment by nhielost** [comment]
Thanks for the reply.

Unfortunately, that log file is not applicable to this issue since it seems that the plugin is never loaded. Could you try to provide a log file that includes loading this plugin? (Try using the log file associated with the crash.)

**Comment by nhielost** [comment]
Also, try the new update if you can.

**Comment by JoqniX** [comment]
Ah it still crashes for me with the latest update~ 2.1.1 oof ;w; 
![image](https://user-images.githubusercontent.com/54277349/201409193-087685ae-c5ca-431c-8c0c-b017239222d4.png)
[Crash 2022-11-12 00-11-12.txt](https://github.com/nhielost/obs-midi-mg/files/9992662/Crash.2022-11-12.00-11-12.txt)


also for the last log~ i didnt load the plugin cuz you had asked for a normal log right~ i cant get the normal log if obs crashes on startup~ idk if its possible to get the log~ but ill send the latest log anyways here~
[2022-11-12 00-11-09.txt](https://github.com/nhielost/obs-midi-mg/files/9992671/2022-11-12.00-11-09.txt)

oh wait it does get the log nvm~ hope this helps ~

**Comment by JoqniX** [comment]
a part of me thinks its either one of the plugins i have installed causing this bout also dunno~ can it be cuz of too many plugins installed? but still how come older versions of obs-midi-mg plugin works?

**Comment by nhielost** [comment]
Based on what I have seen in your crashes and logs, I think that it is this plugin that is causing your issues, but I still don't know why exactly yet. 

I'm going to ask for one more thing from you - can you provide the config file? It should be located under the `plugin_config` folder where the crashes and logs are. There should be a file under the obs-midi-mg folder called `obs-midi-mg-config` - that is the file I want.

**Comment by JoqniX** [comment]
[obs-midi-mg-config.txt](https://github.com/nhielost/obs-midi-mg/files/9993155/obs-midi-mg-config.txt)
as github doesnt allow json files to be shared sadly~ i copy pasted the contents of the file to a txt file~ i hope this is okie?

**Comment by JoqniX** [comment]
oh wait deleting the config helped ??? obs finally launched yay!  wait~ so did the crash happen cuz the config was outdated with old setup~ and you've done alot of new changes ever since~ would that be the case?

**Comment by nhielost** [comment]
I see the problem now. You were using a really old version of the plugin when the data was saved, and the new version won't accept that anymore.

It seems that you have found the solution to the problem. Even so, I'm glad I could be of assistance!
