### ISSUE TITLE
Magnitude is NOT saved between OBS launches for Source Scale

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#39]
With version 2.1.0 and now also with 2.1.1 the Magnitude is NOT saved between OBS launches for Source Scale.

So for versions prior to 2.1.0, once set up the Source Scale options would work between OBS launches without any further modification.

Now I need to manually go through each Source Scale binding and reenter the non-zero magnification, after which my source will show and react to my midi cc.

Sure, when each binding screen initially pops up when I go to reenter the values I had had in there from the last launch, the magnification defaults to 1 (I was using a different value of 1.5 on several and 10 on another), but the plugin will behave like it has a 0 magnitude upon launch until I manually reenter my desired values, and so the source doesn't show (0 magnitude = never shows).

**Comment by nhielost** [comment]
Thanks for the feedback.

I see what you're saying. I have it set so that the value displayed in the field on load doesn't actually change the value until one of the buttons is clicked (otherwise all of the values would reset and the plugin wouldn't work). I guess this bug has been fixed when creating *new* bindings instead of already existing bindings.

I know this might sound bad, but you will have to fix all of them so that it will be correct the next time. This is something I cannot implement because of other things breaking. But hey, this is a one time deal, so you only have to do it once!

**Comment by lcalder** [comment]
got it. Thanks

**Comment by lcalder** [comment]
I must be missing something...
I just deleted all 5 bindings for my midi pedals which scale a color source as the midi pedal is pressed to demonstrate the fact the pedal is being pressed and by how much.
I then created new bindings for each one (new version 2.1.1) with a magnitude of 1.5
They worked.
I then exited OBS and relaunched.
No sources were scaled when I pressed the pedals anymore (they have a 0 magnitude).
I then went into the plugin and clicked the magnitude increment button to increase the magnitude from the shown value of 1 (which is plugged in by the software when I open that view, because the plugin is not correctly saving prior to exit / or initializing upon launch) to 1.5
My sources then scaled correctly again. Until I exit OBS.

**Comment by lcalder** [comment]
BTW, that is what I have been doing these last few days, after the update. Each time I launch, I check my midi pedals and they don't work. Then I open the plugin settings and visit each binding and click the right increment button once to move the displayed magnitude from 1 to 1.5.
It will then work for the rest of the session.

Before the update, I didn't have to do this. Each time I launched OBS the pedals just worked without doing anything with the plugin.

Is there a special save button I have to use?
Other modifications seem to save just fine by making the change or creating the binding and then X'ing out of the plugin interface..

**Comment by nhielost** [comment]
After investigating, it turns out there is a massive bug when setting the values on startup. I will be releasing a fix shortly.

**Comment by nhielost** [comment]
Redownload the 2.1.1 version - I've updated the installers with the bugfix.

**Comment by lcalder** [comment]
I redownloaded and this now appears to be working between launches just fine.
Thanks for the amazing plugin, and for the quick response and bugfix.
