### ISSUE TITLE
"Replay buffer" actions

### ISSUE THREAD

**Issue by KiriakBelyakov** [nhielost/obs-midi-mg#4]
This plugin doesn't have "Save replay" and "Toggle replay buffer". Previous MIDI plugin that I used before and still not updated for OBS Studio 28 has these.
Can you please add these actions? Thank you.

**Comment by nhielost** [comment]
Thanks for the feedback!

I will take these into consideration for the next minor update (1.3.0). (They will likely be included.)

**Comment by nhielost** [comment]
The newest update (v1.3.0) has addressed this issue. This feature is now included.

Again, thanks for the feedback!
