### ISSUE TITLE
Would it be possible to have a magnitude for Move Source?

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#40]
Move source will only move between a maximum and minimum value as set in the source properties (size? or bounding box size?) not sure which...

In order to slide, say, the right edge of a source close to, or even beyond (not really necessary) the left edge of the source there must be a way to override the source size limits.

I am trying to have a Zoom window source repositioned to my liking by using Rotate Source, Zoom Source and Move Source X and Move Source Y so that I can effectively zoom into any portion of the Zoom Application window. Sometimes what I wish to enlarge is up in the upper right or left quadrant of the application window(source) and because my X and Y are limited as to how far they can move, I can't always zoom into ANY part of the source and center it the way I wish. So maybe allowing a magnitude option similar to Source Scale would be a way to allow such behavior?

I really can't thank you enough for this wonderful plugin. Is there a patreon or other account where you accept tips?
Thanks again.

**Comment by lcalder** [comment]
Just checked and, to be precise, I can't get the edge of a source to move past the center point. So, for example, the right edge moved left cannot go past the center (or 50% of the screen width). The left source edge cannot be moved right using the sliders past the center of the original position, and so on for the top and bottom edges...

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.2.0).

Again, thanks for the feedback!
