### ISSUE TITLE
Transitions

### ISSUE THREAD

**Issue by BGroc** [nhielost/obs-midi-mg#42]
Hi, I'm french, sorry for my bad english.
The transitions section crach OBS on my mac.
There is an option to click on quick transitions (cut and fade) ?

**Comment by nhielost** [comment]
Thanks for the feedback!

What exactly crashes in the Transitions section? Something specific or just the action in general?

Also, quick transitions are not distinguishable at the moment, but I'll look into it.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.2.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
