### ISSUE TITLE
Awesome work! Some suggestions...

### ISSUE THREAD

**Issue by HumanalizerVisualien** [nhielost/obs-midi-mg#43]
- by Copy Bindings to other Device: Option: _Including Selected/Unselected_ or maybe even to select wich or both to copy
- to order the parameterlist per drag&drop would be nice
- maybe a button witch turn on midi-learn function and let jump the curser to the connected binding...

But forget all of this suggestions, if you work **on the Filtersettings**, i will love you for(ever) this!...and you will be the hero, who open OBS to _Live Performing Visual Artists_ 

Look a little sample whats already possible thx to your plugin...more? here: https://t.me/Human_Alien_Visualizer

https://user-images.githubusercontent.com/110275767/202856006-8cdd4380-f1c2-4405-90ed-470ca01d4ca6.mov

**Comment by nhielost** [comment]
Thanks for the feedback!

I appreciate the suggestions. Maybe some of them will sneak in the next update...
