### ISSUE TITLE
Toggle indication

### ISSUE THREAD

**Issue by deffuseyou** [nhielost/obs-midi-mg#44]
How can I set it so that the LED on the midi controller lights up when you click on the adjacent one (mute indication). I tried to implement it using "Send massage", but I could only make the indicator light up, and when you press it again, it does not turn off.

**Comment by nhielost** [comment]
Thanks for the feedback!

If I am understanding correctly, you would like the light to activate when the mute is on, and to deactivate when it is off. Currently, this can be done with two separate bindings - one for muting and one for unmuting.

If something else is intended (i.e. I am assuming incorrectly), please let me know, as I intend to add functionality to the MIDI action soon.

**Comment by deffuseyou** [comment]
I want to make it so that when you press the button, the channel mutes, and when you press it again - unmute. And when the channel is in mute, the indicator is on and vice versa.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.2.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
