### ISSUE TITLE
Unable to see hotkeys?

### ISSUE THREAD

**Issue by gabryg66** [nhielost/obs-midi-mg#45]
Hi there,
I am trying to fire some sounds via hotkeys, configuring some Novation launchpad's keys. 

On OBS Hotkeys I have set num 7 to show and hide the sound. This works.
However on obs-midi setup once I have selected Hotkeys - Activate Hotkey, I see 'Refresh cache of current page' displayed and I am not able to select an appropriate hotkey.
![Screenshot 2022-12-02 at 02 17 02](https://user-images.githubusercontent.com/119642036/205199898-ed154142-a54a-4c9e-9cc6-57d6afdc3aeb.png)
![Screenshot 2022-12-02 at 02 17 44](https://user-images.githubusercontent.com/119642036/205199900-fd3841f7-29e0-4a15-b16d-65925a327846.png)

What I am trying to achieve is being able to press a midi key on the novation launchpad and fire a previously set hotkey.

Not sure if I have explained it correctly. How do I fix this?

thanks 
Gabriele

**Comment by nhielost** [comment]
Thanks for the feedback!

You can show or hide a source in a scene with a Video Sources action. (I know it is improperly named.) If only showing or hiding a source is what is intended, this is the best option.

On the other hand, the Hotkeys action is currently being worked on. Currently, only non-OBS (browser, other plugins, etc.) hotkeys are selectable, and I intend to change this soon.

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.2.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
