### ISSUE TITLE
Would it be possible to add an "INVERT" checkbox to the appropriate functions?

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#46]
For example MOVE or ROTATE functions, as they receive input in the range 0-127, would map to an increase in the mapped value in the function, or a DECREASE in the case of the "INVERT" checkbox being selected....

**Comment by nhielost** [comment]
Thanks for the feedback once again!

This is a great feature request, and likely will be implemented soon. Thanks again for all of your support!

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.2.0).

Once again, thanks for the feedback!
