### ISSUE TITLE
HotKey Action does not work properly if the Hotkey name has a duplication

### ISSUE THREAD

**Issue by birdbyrd** [nhielost/obs-midi-mg#47]
Hi there! again great work 👏🏻

Not sure if you can help with this little issue on Hotkey action but when it has a duplication on key names.

<img width="1020" alt="Screenshot 2565-12-11 at 22 03 22" src="https://user-images.githubusercontent.com/19778412/206911311-8bc4649d-55c2-4b70-9355-c57204da6799.png">

The issue issue is:

- From the screenshot, I have 2 items of "Save Replay" hotkey (this come from source-record plugin - I have this enable on 2 of video input source)
- Assume I select the second "Save Replay"
- It will always use the first "Save Replay" when I trigger this macro

Let me know if you need further information. 

Thank you

**Comment by nhielost** [comment]
Thanks for the feedback, and my apologies for replying so late!

Fortunately for you, the Hotkeys action is currently getting a makeover. This has already been taken into consideration and will be present in the next update. I appreciate the request!

**Comment by nhielost** [comment]
This issue has been resolved as of the latest update (v2.2.0). If this issue persists, please create another issue.

Again, thanks for the feedback!
