### ISSUE TITLE
OBS Lagging out with faders

### ISSUE THREAD

**Issue by Mushiiies** [nhielost/obs-midi-mg#48]
Using a Korg NanoKontrol2, I am trying to create bindings for the faders to control the audio source volumes. However it seems to completely choke up when using the faders, the audio starts chopping and OBS slows down. As though the messages are backlogging and starting to delay until it becomes un-usable.
Not sure if I have set it up wrong, or the device is not suitable?

**Comment by Mushiiies** [comment]
The indicated Source Volume flickers when this happens. So it is rapidly moving left and right as though the value is constantly changing

**Comment by nhielost** [comment]
Thanks for the feedback, and my apologies for replying so late!

I have a couple of questions.
Firstly, do you use a lot of bindings? If so, are they using the same message as an input?
Secondly, could I have a look at a log file of when this is occurring?

**Comment by nhielost** [comment]
Also, does this still occur with the new version v2.2.0?

**Comment by Mushiiies** [comment]
I've just done some trouble shooting, the issue is associated with using a Source Dock.
Removing Source Docks has solved the issue :)
(https://obsproject.com/forum/resources/source-dock.1317/)

**Comment by nhielost** [comment]
I appreciate the confirmation. Thanks for the feedback!
