### ISSUE TITLE
Plugin won't show up in OBS v28 on Pop_OS Linux

### ISSUE THREAD

**Issue by DieNeueUnterschicht** [nhielost/obs-midi-mg#5]
Hi,
installed the plugin via the .deb package. Unfortunately the plugin won't show up under Tools.
Any help would be greatly appreciated, Thanks.

**Comment by nhielost** [comment]
Thanks for your feedback!

Can you post the most recent log file? This will help in identifying the issue and possibly fixing it.

**Comment by DieNeueUnterschicht** [comment]
[2022-09-02 00-26-02.txt](https://github.com/nhielost/obs-midi-mg/files/9473866/2022-09-02.00-26-02.txt)

**Comment by DieNeueUnterschicht** [comment]
Okay... after unpacking the deb file, and moving the provided file to the .config folder structure of OBS I'm now able to launch the plugin in OBS. Unfortunately it doesn't show any  devices (Korg nankontrol 2)

**Comment by nhielost** [comment]
This issue has been resolved as of the latest release (v1.4.0). If the issue persists, please create another issue.

Again, thanks for the feedback!
