### ISSUE TITLE
Superhero!!! 100'000 Thx for the Filtersettings, just awesome...

### ISSUE THREAD

**Issue by HumanalizerVisualien** [nhielost/obs-midi-mg#51]
It is maybe possible to add like a switch over a binding between devices? That will be the ultimate thing...

The Idea is, that i can switch for example between IAC1/IAC2....like Scene Switching just for devices....

**Comment by nhielost** [comment]
Thanks for the feedback, and the patience!

I am unsure what you are requesting. Do you want a binding that will flip flop between devices, or a binding option TO switch the devices?

**Comment by HumanalizerVisualien** [comment]
oh sorry, since 3 days i own a Behringer B-Control BCR2000…that mean, i don’t need anymore this request, cuz this machine can do everything i wish for….thank you for your incredible work, nature’s spirits will show them magic powers to you…!

take a look here i you like: thenaturespiritshow.com

best regards
human alien visualizer

**Comment by nhielost** [comment]
Oh! Well, good luck out there. Thanks for your enduring patience and outstanding ideas.
