### ISSUE TITLE
no negative values when setting the source offset

### ISSUE THREAD

**Issue by vicobs** [nhielost/obs-midi-mg#52]
when I adjust the movement of the source vertically, there are only values 0-127, which corresponds to the position of its upper left edge. It can only move from the top of the screen to the bottom, but it is often necessary to move the source above the top of the screen, so it's worth adding values less than 0, or the ability to control the value boundaries.

**Comment by nhielost** [comment]
Thanks for the feedback, and the patience!

I am currently implementing this feature. Come back soon for updates, and don't hesitate to provide feedback or suggestions!

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.3.0) - use the Custom bounds option to extend the bounds past the screen resolution.

Once again, thanks for the feedback!
