### ISSUE TITLE
[Feature request] MIDI Thru

### ISSUE THREAD

**Issue by LenweSaralonde** [nhielost/obs-midi-mg#53]
We may need to control several applications simultaneously using the same MIDI device (for example OBS and a sound board). Unfortunately, most MIDI drivers allow only one application at a time.

To address this problem, some applications have a **MIDI Thru** option to forward incoming MIDI messages from the **MIDI In** device to a selected **MIDI Out** device that can be a virtual cable such as one created using [loopmidi](https://www.tobias-erichsen.de/software/loopmidi.html).

### Solution proposal

Add a **MIDI Thru Device** in the setup menu to forward all the incoming MIDI messages from the **Active Device** to the selected **MIDI Thru Device**. 

![image](https://user-images.githubusercontent.com/34239920/214338861-e1746537-af98-4315-b179-6db5fc01868e.png)

This is optional and can be enabled with a checkbox. The list options are the available MIDI out devices.

**Comment by nhielost** [comment]
Thanks for the feedback, and the patience!

I like this idea! This might not be placed in that spot in the menu described in your image, but it likely will make it in somewhere. I realize how important MIDI Thru functionality is, so this is a top priority.

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.3.0) - it can be located in the Preferences menu.

Once again, thanks for the feedback!

**Comment by LenweSaralonde** [comment]
It works great, thanks ! This definetly makes the configuration much easier.

However, I might found a bug, not a big deal but I created another ticket for that #59
