### ISSUE TITLE
Filters / Custom Filter Settings doesn't allow to adjust 

### ISSUE THREAD

**Issue by LenweSaralonde** [nhielost/obs-midi-mg#58]
The Filters / Custom Filter Settings only allows to change one fixed parameter of the filter. For example, the "Apply LUT" filter has 2 parameters : "Amount" (slider, from 0 to 1) and "ignore alpha" (checkbox). The Custom Filter Settings only allows to change the value of the ignore alpha checkbox. It would be great to add another combo box to choose between the "Ignore alpha" and "Amount" and being able to map min-max value of the slider to MIDI 0-127 (or 127-0) values.

**Comment by nhielost** [comment]
Thanks for the feedback!

Try the newest update (v2.3.0) and see how that works for you.

**Comment by LenweSaralonde** [comment]
Works exactly as I wanted. Thanks a lot!

https://user-images.githubusercontent.com/34239920/228965608-022b39d4-f230-4433-a5df-9d1de57a5ba6.mov

**Comment by nhielost** [comment]
I'm glad I could help, and as always, I appreciate the feedback!
