### ISSUE TITLE
Bindings from other than the active device get activated when using MIDI thru

### ISSUE THREAD

**Issue by LenweSaralonde** [nhielost/obs-midi-mg#59]
I discovered a quite strange behavior after the [MIDI thru feature](https://github.com/nhielost/obs-midi-mg/issues/53) was implemented. I'm not sure this is intentional so here is an bug ticket.

## How to reproduce
1. Set some bindings for a MIDI hardware device.
2. Create a virtual MIDI device using [loopMIDI](https://www.tobias-erichsen.de/software/loopmidi.html) and 
3. Set bindings for the virtual device.
4. Enable MIDI thru from the hardware device to virtual device
5. Set the hardware device as the active device
6. Send some MIDI messages using the hardware device that has matching bindings on both the hardware and the virtual devices.

## Actual result
The bindings for the virtual device react from messages forwarded by the hardware device, even if the virtual device is not the active one.

## Expected result
The bindings for the virtual device do not react since it's not the active one.

**Comment by nhielost** [comment]
Thanks for the feedback!

I have found a fix to this problem, and it will be implemented soon.

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.3.1).

Again, thanks for the feedback!
