### ISSUE TITLE
Crashes instantly on loading OBS v28

### ISSUE THREAD

**Issue by lcalder** [nhielost/obs-midi-mg#6]
It crashes as soon as I launch obs v28.0.0. I had tried on Rc1 and Rc2 but those crashed as well.
Obs doesn't even display the screen. Just "Ooops! OBS has crashed."
I tried in a clean install with no other plugins and still crashed.
Please find crashlog attached.
[Crash 2022-09-02 02-33-29.txt](https://github.com/nhielost/obs-midi-mg/files/9476939/Crash.2022-09-02.02-33-29.txt)

**Comment by nhielost** [comment]
Thanks for the feedback!

Could you also post the normal log file? This will help in identifying the issue.

**Comment by nhielost** [comment]
The newest update (v1.2.2) has addressed this issue. If this issue persists, please create a new issue for that update.

Again, thanks for the feedback!
