### ISSUE TITLE
obs-midi-mg in obs-studio29.02 cannot load

### ISSUE THREAD

**Issue by QidongLi** [nhielost/obs-midi-mg#61]
I downloaded your source code and compiled it. Then, I copied the obs-midi-mg.dll and obs-midi-mg.pdb to the plugin directory in the obs studio 29.02 installation directory. When I ran obs.exe, I couldn't find the obs-midi-mg plugin in the tools menu. But I use the library you compiled and it works well. When compiling the obs-midi-mg source code, I used the obs source code version of obs studio-29.0.2, the QT dependency package is windows-deps-qt6-2023-03-30-x64.zip, and the other dependency packages are windows-deps-2023-03-26-x64.zip. The download link for the dependency package is: https://github.com/obsproject/obs-deps/releases
    Any assistance / suggestions would be appreciated.
Thank You

**Comment by nhielost** [comment]
This issue is being closed due to inactivity. Please create a new issue if it persists.

(P.S. OBS Studio updated their CMake scripts so look into that if you are still having trouble.)
