### ISSUE TITLE
MIDI notes not recognized

### ISSUE THREAD

**Issue by ItsBrokenScreen** [nhielost/obs-midi-mg#62]
I just installed this plugins a few minutes ago as of writing this report and although it's very straightforward and simple to use, I can't assign a binding to a note on my keyboard because it's not detecting it when I press it. I tried with both the "listen once" and "listen continuous" buttons and nothing. It only says "cancel" when I click on those buttons and no matter what keys and buttons I press on my keyboard, it doesn't seem to be detecting anything. I also tried pressing the key I was trying to assign to the binding outside of the menu to see if it would work and nothing happened either. It's possible that I might've missed something for setting it up, but I'm not sure what the issue may be, so any help is welcome!

PS.: I'm using an Alesis Vmini keyboard if that helps!

**Comment by nhielost** [comment]
Thanks for the feedback!

Could you please provide an OBS log file of when you attempt to listen to a MIDI message? This may help in identifying the issue.
