### ISSUE TITLE
obs-midi-mg not installing MacBook Pro (15-inch, 2017)

### ISSUE THREAD

**Issue by VintageMuso** [nhielost/obs-midi-mg#63]
I am trying to install obs-midi-mg onto a MacBook Pro (15-inch, 2017),. 2.8 GHz Quad-Core Intel Core i7 with OBS 29.0.2(64 bit). The OS is  macOS Monterey 12.6.1.

I have tried the installing from the following files
 - obs-midi-mg-2.3.0-macos-universal.pkg
 - bs-midi-mg-2.3.0-macos-x86_64.pkg

It took me awhile to find what appear to be the latest files so my earlier installs were from
obs-midi-0.9.3-ALPHA-3.61-macOS
obs-midi-0.9.3-ALPHA-3.66-macOS

In all cases, which included restarts of the laptop, I have not seen the OBS midi option appear in the Tools menu.

Any suggestions on how to get it working?

**Comment by nhielost** [comment]
Thanks for the explanation!

I am unable to reproduce your situation, but could you please provide if the plugin is installed in the proper place? (`/Library/Application Support/obs-studio/plugins` might be the path to it, I'm not sure)

Providing a log file from OBS of you attempting to access the plugin here could be helpful as well.

**Comment by VintageMuso** [comment]
Thanks for getting back to me.

The plugin is in the folder. I have attached two screen shots. The plugins folder and the OBS Tools menu. 

![Plugins folder](https://user-images.githubusercontent.com/130135846/231607709-a50ba24c-65f9-4659-94b7-deb026626421.png)
<img width="704" alt="OBS Menu" src="https://user-images.githubusercontent.com/130135846/231607718-389d251d-b36e-435b-a78e-26c11bfbd244.png">

**Comment by s00500** [comment]
Edit: after checking the global directory I found it (in /Library/Application Support/obs-studio)
Then moved into the Library living in my homefolder to the same location and voila it works!

**Comment by nhielost** [comment]
This issue is being closed due to inactivity. Please create a new issue if it persists.
