### ISSUE TITLE
How do I remove disconnected MIDI devices from the "Active Device" dropdown?

### ISSUE THREAD

**Issue by jernanigans** [nhielost/obs-midi-mg#64]
I would like to clean up the "Active Devices" menu.  It currently shows every MIDI device that I have ever connected to my computer, even though some of them are no longer connected.  Is there a way to do this?

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/3045423/230626777-f2f5ad32-8f32-458f-8d91-b63ba46b2c18.png">

**Comment by nhielost** [comment]
This issue has been implemented as of the latest update (v2.3.1).

Again, thanks for the feedback!
