### ISSUE TITLE
OBS 29.0.2 crashes with the new released Version 2.3.1

### ISSUE THREAD

**Issue by Sebuku** [nhielost/obs-midi-mg#65]
Hi there, thx for the plug in

But it seems that OBS 29.0.2 and version 2.3.1 are not working together OBS always crashes when i choose the Plug In.
If i use the 2.3 it works 

Which Infos do you need ?

System: Win10 OBS 29.0.2(+your PlugIn nothing more) and the nanoKontrol2

Thank you

**Comment by nhielost** [comment]
Thanks for the feedback!

Could you please provide both a crash log and a normal log associated with the crash? This will give me insight into what is going on.

**Comment by comadrejo** [comment]
Happened to me too. Checked my OBS logs and found this:

```
02:51:21.091: Failed to load 'es-ES' text for module: 'obs-midi-mg'
```
Changed OBS lang to English and obs-midi-mg setup stopped crashing

**Comment by comadrejo** [comment]
Same over here con arm64 Mac, a Launchpad Pro X and OBS 29.1.0-beta4. 2.3.0 works alright

**Comment by Sebuku** [comment]
Hi,
will do hope this helps you
Log from the Crash: https://obsproject.com/logs/OFCyiJadXqAn4Ftx
Log file with the plugin 2.3: https://obsproject.com/logs/NLXZXxDTf6MOksbE

**Comment by nhielost** [comment]
Thanks for the reply.

I appreciate the logs, but could you please provide two more things:
- A ***log file*** of when OBS Studio crashes (not a crash log)
- Your configuration file (in the `plugin_config/obs-midi-mg` folder - convert it to a text file before uploading it to this thread)

I am pretty sure that I know what is going on, but this information is just to make sure.

**Comment by Sebuku** [comment]
Hi, hope this will help
[2023-04-18 09-41-35.txt](https://github.com/nhielost/obs-midi-mg/files/11285120/2023-04-18.09-41-35.txt)

And the secound file
im not sure where to find
\Program Files\obs-studio\data\obs-plugins\obs-midi-mg <-there is only the local 
\Program Files\obs-studio\obs-plugins\64bit <- there are the .dll and .pdb files


But somthing has changed, no i can Open the PlugIn 2.3.1

Step By Step

Install a clean OBS 29.0.2 version
Unziped the PlugIn 2.3.1
OBS crashed after opening tools and selecting obs-midi-mg setup
Unziped the PlugIn 2.3
Reopend OBS and it worked opening the tool selection obs-midi-mg
so this was my last change

Now I unpacked the 2.3.1 again into OBS folder, and without any changes its working now

![WorkingPlugIn231](https://user-images.githubusercontent.com/131148107/233342437-8ae6cc36-532c-4d40-8402-a05bd0e4d3c7.JPG)

**Comment by ogmkp** [comment]
Version 2.3.1 has been removed by the developer, so if you're good with it, please close this ticket.

**Comment by Sebuku** [comment]
Sorry for late responese  sure thx for  your supporrt and work
