### ISSUE TITLE
Failed with Fedora 38, OBS 29.0.2, obs-midi-mg 2.3.0 and 2.3.1

### ISSUE THREAD

**Issue by OlegoroV** [nhielost/obs-midi-mg#66]
Didn't able to run OBS with this plugin.

```
info: [obs-midi-mg] Loading plugin...

raw_alsa_helpers::enumerator::enumerate_devices: cannot determine device number: Inappropriate ioctl for device

terminate called after throwing an instance of 'libremidi::driver_error'
  what():  raw_alsa_helpers::enumerator::enumerate_devices: cannot determine device number: Inappropriate ioctl for device
```

I took files from deb package.
I'm not good in compiling from sources and didn't find any instruction for this plugin.

**Comment by ogmkp** [comment]
Seems we have the same problem #83

**Comment by nhielost** [comment]
This issue is being closed due to inactivity. Please create a new issue if it persists.

(P.S see #83 for updates.)
