### ISSUE TITLE
Feature request: Allow custom values greater than 100% and lower than 0

### ISSUE THREAD

**Issue by basisbit** [nhielost/obs-midi-mg#68]
When using custom bounds that the MIDI 0-127 value get mapped to, it is not possible to set percentage values greater than 100%. However for example when setting the loudness of an audio source, OBS supports higher values like 150% for example which adds a gain to the input signal, making a too quiet signal loud enough. 

Similarly, when using MIDI 0-127 mapped to the delay setting of an audio source, it should be possible to specify less than 0, otherwise it currently is not possible to adjust the audio delay where the audio source is already too late compared to a video source. OBS supports this.

Might be worth it to just remove those limits in the code of obs-midi-mg and let the user make sure they specify valid values.

**Comment by nhielost** [comment]
This functionality is currently available in beta, and will be released outside of beta soon.

Again, thanks for the feedback!
