### ISSUE TITLE
Crash open OBS 28

### ISSUE THREAD

**Issue by xDreams0** [nhielost/obs-midi-mg#7]
Hello,
I am having a problem with the plugin following the switch to OBS 28!
The latter crashes directly on launch.

Here are the 2 error logs
[2022-09-02 19-34-37.txt](https://github.com/nhielost/obs-midi-mg/files/9480220/2022-09-02.19-34-37.txt)
[Crash 2022-09-02 19-34-39.txt](https://github.com/nhielost/obs-midi-mg/files/9480221/Crash.2022-09-02.19-34-39.txt)

**Comment by nhielost** [comment]
Thanks for the feedback!

This issue has been brought to my attention by multiple people, and I appreciate the log file as others have not provided one (yet). I now know the problem and it will be fixed soon.

**Comment by xDreams0** [comment]
Thanks.

I hope it will be quickly corrected, because I have just upgraded to OBS 28 and you are the only one to provide a Midi plugin which is up to date for this version.

I just wanted to know, would you have a visual of the plugins?
See how is the UI interface.

**Comment by nhielost** [comment]
The newest update (v1.2.2) has addressed this issue. If this issue persists, please create a new issue for that update.

Again, thanks for the feedback!

Also, here is the UI interface you wanted to see (the bottom is cut off):

![obs-midi-mg-ui-img](https://user-images.githubusercontent.com/64743457/188283167-3a02dfc8-b336-4076-9310-9f974606f633.png)
