### ISSUE TITLE
Not seeing the plugin in tools

### ISSUE THREAD

**Issue by darrinstern** [nhielost/obs-midi-mg#71]
Would anyone know why I can not see the plugin? I'm new to all of this, I have OBS 29.1.2 installed on a Intel based Mac. Help please....thanks.

**Comment by andrew0302** [comment]
Same issue, on intel based mac running Ventura.

**Comment by Gaurav-Bhard** [comment]
Same issue on mac M1

**Comment by nhielost** [comment]
This issue is being closed due to inactivity. Please create a new issue if it persists.
