### ISSUE TITLE
Running obs-midi-mg Setup crashes OBS 29.1.3

### ISSUE THREAD

**Issue by austin2Go** [nhielost/obs-midi-mg#73]
[Crash 2023-06-20 13-01-39.txt](https://github.com/nhielost/obs-midi-mg/files/11804774/Crash.2023-06-20.13-01-39.txt)

I just updated OBS today and just installed this plug-in and OBS crashes when attempting to enter the Setup for the plug-in via the Tools menu in OBS.

**Versions**
OBS 29.1.3
obs-midi-mg 2.3.1

**Comment by gravelfreeman** [comment]
I can confirm this behaviour, plugin doesn't work.

**Comment by austin2Go** [comment]
> Uninstalled version 2.3.1 and installed version 2.3.0 and it's working great!

I did the same after seeing another post saying this worked. Also works for me

**Comment by flexiondotorg** [comment]
I am also seeing this issue on 29.1.3

**Comment by ogmkp** [comment]
Version 2.3.1 has been removed by the developer, so if you're good with it, please close this ticket.

**Comment by nhielost** [comment]
This issue is being closed due to inactivity. Please create a new issue if it persists.
