### ISSUE TITLE
Performing multiple actions

### ISSUE THREAD

**Issue by PeterN** [nhielost/obs-midi-mg#75]
Currently it seems like the design is one action per binding, and the only way to get around that is to create a binding with an internal action, as that can then trigger a set of other bindings.

For every button press I'd like to issue multiple actions:
1) perform an action
2) send a multiple note-off to turn off status LEDs
3) send note-on to turn on a new status LED.
While this seems possible it means I need at least 4 bindings just for one button -- and setting this up seems long winded.

Are multiple actions per binding in the plan, or is this the way it should be?

Additionally, it seems its not possible to chain from internal to other internal bindings.

**Comment by nhielost** [comment]
This functionality is currently available in beta, and will be released outside of beta soon.

Thanks for the feedback!

**Comment by PeterN** [comment]
Fantastic!
