### ISSUE TITLE
Midi multiple input crash

### ISSUE THREAD

**Issue by xDreams0** [nhielost/obs-midi-mg#8]
Hello,

The problem is now different.
I use a Korg NanoKontrol 2 as a Midi with several software to manage the operation.

First, I use Voicemetter which manages my speakers as well as my music for volume adjustment and mute via my Midi, to do this, I use LoopMidi as well as Midi-Ox in order to start from a device to operate 2 at the same time.

When I put your plugin, in version 1.2.2, it still crashed, so I disconnected my midi, closed the Midi-OX and LoopMidi software, it still didn't work. I closed Voicemetter and the OBS started fine.

I don't understand why with your plugin I can't use my Midi with the configuration I had.
Your plugin asks the Midi for full control without any other device being able to use it.

I did not have this problem with the plugin
obs-midi 0.9.3-Alpha-3x

Here are the log and crash files

**Voicemetter On (and LoopMidi & Midi-OX)**
> [2022-09-04 01-00-18.txt](https://github.com/nhielost/obs-midi-mg/files/9483544/2022-09-04.01-00-18.txt)
> [Crash 2022-09-04 01-00-21.txt](https://github.com/nhielost/obs-midi-mg/files/9483546/Crash.2022-09-04.01-00-21.txt)

**Voicemetter Off** 
> [2022-09-04 00-57-54.txt](https://github.com/nhielost/obs-midi-mg/files/9483545/2022-09-04.00-57-54.txt)

**Comment by nhielost** [comment]
Thanks for the feedback.

I see that you are attempting to use the device with multiple programs, and that in combination with this plugin it causes an error where OBS crashes. 

This will take time to fix as I have to reroute certain aspects of the program, but this will be fixed by the next update.

Thank you for your persistence in reporting this issue.

**Comment by datlaunchystark** [comment]
I had the same problem too, I posted it here: https://github.com/nhielost/obs-midi-mg/issues/10

**Comment by nhielost** [comment]
The newest update (v1.3.0) has addressed this issue. The fix has finally come. If this issue persists, please create a new issue for that update. 

Again, thanks for the feedback!
