### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by TheyNay** [nhielost/obs-midi-mg#88]
Trojan:Win32/Wacatac.B!ml detected by Microsoft Defender. Is it normal? Did someone alter the code? Need some help with that. Also trying to install on OBS 30.0.0.
(Virus detected both by my navigator which cancelled the download, Virus Total and Microsoft Defender)

**Comment by szszoke** [comment]
You should post the download link that you used.

**Comment by nhielost** [comment]
This issue is being closed due to inactivity.
