### ISSUE TITLE
Support for Bluetooth MIDI expected?

### ISSUE THREAD

**Issue by DanBourque** [nhielost/obs-midi-mg#9]
I have my Roland FP-30x connected via **Bluetooth MIDI** to my PC (works with Synthesia, for example), but my device doesn't show up in obs-midi-mg's Devices list during setup. Will this be supported in the future?

**Comment by datlaunchystark** [comment]
Bluetooth MIDI on Windows is only available to Metro apps unfortunately as far as I know, however there is a workaround you can try using an Metro app called MIDIberry which can be downloaded on the Microsoft Store, and you can use a program called loopMIDI.
In loopMIDI, you add a loopback MIDI port.  In MIDIberry, you set the input to your Roland FP-30x and the Output to the loopMIDI port.  Then you tell obs-midi-mg to make mappings to the loopMIDI port.

This has worked for me for other programs (haven't tested this with obs-midi-mg) however there are a few limitations to this workaround that I should mention:
1. With my experience using this method with a nanoKontrol Studio Bluetooth MIDI controller, sometimes I have to restart MIDIberry for the connection to work again.
2. As far as I know, there's no way to send MIDI out (for like faders or LEDS) through this method.

Here are the links to the software I mentioned:
loopMIDI: https://www.tobias-erichsen.de/software/loopmidi.html
MIDIberry: https://apps.microsoft.com/store/detail/midiberry/9N39720H2M05?hl=en-ki&gl=ki

**Comment by DanBourque** [comment]
Thanks very much! I appreciate you taking the time to respond so thoroughly. I'll give that a try.
Cheers!

**Comment by nhielost** [comment]
Unfortunately, Bluetooth MIDI is and will remain unsupported due to the MIDI API that supports Bluetooth MIDI on Windows being incompatible with other APIs. This cannot be addressed by me.

@datlaunchystark has provided a great method of getting Bluetooth MIDI devices to appear in the plugin. In many cases, loopMIDI will be your friend.

Thanks for the feedback.
