### ISSUE TITLE
Source Audio Monitor Changed action does not trigger

### ISSUE THREAD

**Issue by Devvypaws** [nhielost/obs-midi-mg#97]
# Description

The "Source Audio Monitor Changed" action does not trigger on changes to the audio monitor type.

# Environment

- **Operating System:** Windows 10 22H2 (19045.3803)
- **Controller:** AKAI MIDImix
- **OBS:** 30.0.2 (64 bit)
    - **obs-midi-mg:** 3.0.0
    - **[input-overlay](https://github.com/univrsal/input-overlay):** 5.0.4
    - **[obs-spout2-plugin](https://github.com/Off-World-Live/obs-spout2-plugin):** 1.8

# Steps to Reproduce

1. Open "obs-midi-mg Setup" dialog
2. Go to "Actions" view
3. Click "Add" button
    - This is your [Test Action]
4. In the "Category" drop down, choose "Audio Sources"
5. In the "Action" drop down, choose "Source Audio Monitor"
6. In the "Audio Source" drop down, choose a source to test
    - This is your [Test Audio Source]
7. In the "Audio Monitoring" section's drop down, choose a value to test
    - This is your [Test Monitor Type]
8. Set up a MIDI message to control an LED or other value you can use to observe changes on your controller
    - This is your [Test MIDI Message]
9. Set up an output binding that triggers [Test Action] and sends the [Test MIDI Message]
10. Change the audio monitoring on the [Test Audio Source] to the chosen [Test Monitor Type]

# Expected Results

The binding is triggered and the change is observed on the controller

# Actual Results

The binding isn't triggered and nothing happens

# Additional Details

- This action was tested with existing MIDI messages that provably operated the LEDs to rule out bad MIDI message setup
- This action was tested with different values for the "Audio Monitoring" drop down, ensuring it wasn't just that specific value

**Comment by nhielost** [comment]
This issue has been resolved as of version 3.0.0. If the issue persists, please create another issue.
