### ISSUE TITLE
Does not work if Midi device is inserted after OBS started

### ISSUE THREAD

**Issue by LMWCoding** [nhielost/obs-midi-mg#98]
Firstly, congrats for the new release, and you have added many features. I am able to get the Midi-out working, which is fantastic (although still need in investigate more on how to config it right).

The issue that I would like to report is that when I have everything working, if I now remove the MIDI device (nanoKontrol2  connected using USB) by unplugging the USB, then reinserting the USB, the obs-midi-mg does not response to the midi device anymore.   Seems that.

**Comment by nhielost** [comment]
Hello!

The official release (v3.0.0) should have this feature now, so go try it out!
